services:
  emischeduler:
    build:
      context: ./
      network: host
    environment:
      - "EMISCHEDULER__SERVER__HOST=${EMISCHEDULER__SERVER__HOST:-0.0.0.0}"
      - "EMISCHEDULER__SERVER__PORT=${EMISCHEDULER__SERVER__PORT:-33000}"
      - "EMISCHEDULER__STORE__PATH=${EMISCHEDULER__STORE__PATH:-data/state.json}"
      - "EMISCHEDULER__STREAM__TIMEOUT=${EMISCHEDULER__STREAM__TIMEOUT:-PT1H}"
      - "EMISCHEDULER__CLEANER__REFERENCE=${EMISCHEDULER__CLEANER__REFERENCE:-2000-01-01T00:00:00}"
      - "EMISCHEDULER__CLEANER__INTERVAL=${EMISCHEDULER__CLEANER__INTERVAL:-P1D}"
      - "EMISCHEDULER__SYNCHRONIZER__REFERENCE=${EMISCHEDULER__SYNCHRONIZER__REFERENCE:-2000-01-01T00:00:00}"
      - "EMISCHEDULER__SYNCHRONIZER__INTERVAL=${EMISCHEDULER__SYNCHRONIZER__INTERVAL:-PT1M}"
      - "EMISCHEDULER__SYNCHRONIZER__WINDOW=${EMISCHEDULER__SYNCHRONIZER__WINDOW:-P1D}"
      - "EMISCHEDULER__EMISHOWS__HOST=${EMISCHEDULER__EMISHOWS__HOST:-localhost}"
      - "EMISCHEDULER__EMISHOWS__PORT=${EMISCHEDULER__EMISHOWS__PORT:-35000}"
      - "EMISCHEDULER__EMIARCHIVE__HOST=${EMISCHEDULER__EMIARCHIVE__HOST:-localhost}"
      - "EMISCHEDULER__EMIARCHIVE__PORT=${EMISCHEDULER__EMIARCHIVE__PORT:-30000}"
      - "EMISCHEDULER__EMIARCHIVE__USER=${EMISCHEDULER__EMIARCHIVE__USER:-readonly}"
      - "EMISCHEDULER__EMIARCHIVE__PASSWORD=${EMISCHEDULER__EMIARCHIVE__PASSWORD:-password}"
      - "EMISCHEDULER__EMIARCHIVE__LIVE_BUCKET=${EMISCHEDULER__EMIARCHIVE__LIVE_BUCKET:-live}"
      - "EMISCHEDULER__EMIARCHIVE__PRERECORDED_BUCKET=${EMISCHEDULER__EMIARCHIVE__PRERECORDED_BUCKET:-prerecorded}"
      - "EMISCHEDULER__EMISTREAM__HOST=${EMISCHEDULER__EMISTREAM__HOST:-localhost}"
      - "EMISCHEDULER__EMISTREAM__PORT=${EMISCHEDULER__EMISTREAM__PORT:-10000}"
    network_mode: host
    volumes:
      - data:/app/data/

volumes:
  data: {}
